# Generated by Django 4.2.4 on 2023-08-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del envase')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Factor de costo')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='envase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketapp.envase', verbose_name='Tipo de envase'),
        ),
    ]
